Traceback (most recent call last):
  File "/home/athekunal/BL-Project/V3/Black-Litterman-Portfolio-Optimization-using-RL/main.py", line 18, in <module>
    run_mlp_bl_sp(args.if_confidence)
  File "/home/athekunal/BL-Project/V3/Black-Litterman-Portfolio-Optimization-using-RL/mlp_bl_sp.py", line 171, in run_mlp_bl_sp
    log_df["Absolute_ret_1"] = [i[0][0] for i in test_env_instance.actions]
  File "/home/athekunal/BL-Project/V3/Black-Litterman-Portfolio-Optimization-using-RL/mlp_bl_sp.py", line 171, in <listcomp>
    log_df["Absolute_ret_1"] = [i[0][0] for i in test_env_instance.actions]
IndexError: invalid index to scalar variable.
Traceback (most recent call last):
  File "/home/athekunal/BL-Project/V3/Black-Litterman-Portfolio-Optimization-using-RL/main.py", line 18, in <module>
    run_mlp_bl_sp(args.if_confidence)
  File "/home/athekunal/BL-Project/V3/Black-Litterman-Portfolio-Optimization-using-RL/mlp_bl_sp.py", line 171, in run_mlp_bl_sp
    log_df["Absolute_ret_1"] = [i[0][0] for i in test_env_instance.actions]
  File "/home/athekunal/BL-Project/V3/Black-Litterman-Portfolio-Optimization-using-RL/mlp_bl_sp.py", line 171, in <listcomp>
    log_df["Absolute_ret_1"] = [i[0][0] for i in test_env_instance.actions]
IndexError: invalid index to scalar variable.